baseURL = "/"
theme = "hugo-whisper-theme"
languageCode = "en-us"
title = "Horus"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Horus is a roles and permissions registerer that makes it easy to work on authorization.'
  homepage_image = 'images/installation.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Horus is a roles and permissions registerer that makes it easy to work on authorization."
    meta_og_title = "Horus"
    meta_og_type = "website"
    meta_og_url = "https://docs-horus.vercel.app"
    meta_og_image = ""
    meta_og_description = "Horus is a roles and permissions registerer that makes it easy to work on authorization."
#    meta_twitter_card = "summary"
#    meta_twitter_site = "@zerostaticio"
#    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/images/logo.png"
      standard  = "/images/logo.png"

  [params.footer]
    copyright_text = '© 2023 Mortazavi'
